In [1]:
import numpy as np


In [8]:
my_list=[1,2,4,46,4.4]
arr=np.array(my_list,dtype=int)

In [9]:
my_list

[1, 2, 4, 46, 4.4]

In [10]:
arr

array([ 1,  2,  4, 46,  4])

In [7]:
type(arr)

numpy.ndarray

In [36]:
arr.shape

(1, 15)

In [59]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

arr=np.array([list1,list2,list3])

In [60]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [66]:
print(arr.ndim)
print(type(arr))
print(arr.size)
print(arr.shape)

2
<class 'numpy.ndarray'>
15
(3, 5)


In [61]:
arr.shape

(3, 5)

In [40]:
arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [41]:
arr.shape

(3, 5)

In [58]:
arr

array([0, 2, 4, 6, 8])

In [43]:
arr[2]

array([11, 12, 13, 14, 15])

In [46]:
arr[1:,1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [52]:
arr=np.arange(0,10,step=2,dtype=int)

In [53]:
arr

array([0, 2, 4, 6, 8])

In [57]:
np.linspace(1,10,num=10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:

list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list3=[11,12,13,14,15]

a=np.array([list1,list2,list3])


print(a.sum()) 
print(a.min()) 
print(a.max()) 
print(a.cumsum())

120
1
15
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]


In [68]:
np.zeros((2, 3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [69]:
np.ones((3,7),dtype=int )

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [78]:
np.empty([2,4],dtype=int)

array([[     94781319461040,     139796931942480,     139796931942544,
            139796931941520],
       [    139796931942800, 3834034675156399409, 6499877569611510062,
            139797672525090]])